{
	"version": 1729895330,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background_-sheet0.png",
		"images/tilemap.png",
		"images/littlegery-sheet0.png",
		"images/littlegery-sheet1.png",
		"images/littlegery-sheet2.png",
		"images/tilemap2.png",
		"images/star1-sheet0.png",
		"images/star1-sheet1.png",
		"images/portal1-sheet0.png",
		"images/portal1-sheet1.png",
		"images/pearly-sheet0.png",
		"images/star2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tilemap4.png",
		"images/sprite4-sheet0.png",
		"images/tilemap5.png",
		"images/deadforest_bg_3-sheet0.png",
		"images/deadforest_bg_4-sheet0.png",
		"images/deadforest_bg_5-sheet0.png",
		"images/clouds_back-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/monster1-sheet0.png",
		"images/monster1-sheet1.png",
		"images/bantengmerah-sheet0.png",
		"images/idle-sheet0.png",
		"images/idle-sheet1.png",
		"images/bird_v002_blue_and_yellow_small-sheet0.png",
		"images/bird_v002_blue_and_yellow_small-sheet1.png",
		"images/heartremovebgpreview-sheet0.png",
		"images/portal2-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/cloud-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/save-sheet0.png",
		"media/y2mate.com - minggir lu miskin ishowspeed.ogg",
		"media/coin.ogg",
		"media/jump.ogg",
		"media/utomp3.com - diamond bling sound effect no copyright sound effects sounds.ogg",
		"media/pearl.ogg",
		"media/utomp3.com - sm64 star sparkle sound.ogg",
		"media/damage (mp3cut.net).m4a",
		"media/damage (mp3cut.net).ogg",
		"media/stage1.ogg",
		"media/stage2.ogg",
		"media/portal.ogg",
		"media/music3.ogg",
		"media/y2mate.com - windah lagu aur auran.ogg",
		"media/ffix.ogg",
		"media/y2mate.com - different heaven safe and sound house ncs copyright free music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}